
privileges = {
    "PRIV_GUEST": 0x00,
    "PRIV_USER": 0x01,
    "PRIV_SEND_MESSAGE": 0x02,
    "PRIV_CREATE_POST": 0x03,
    "PRIV_VIEW_SITE": 0x04,
    "PRIV_VIEW_HIDDEN_POST": 0x05,
    "PRIV_VIEW_ALL_NODE": 0x06,
    "PRIV_ADMIN": 0x07
}